name: mc-publish
on:
  release:
    types: [published]

jobs:
  build:
    runs-on: [ubuntu-22.04]
    steps:
      - name: checkout repository
        uses: actions/checkout@v3
      - name: validate gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: setup jdk ${{ matrix.java }}
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'microsoft'
      - name: make gradle wrapper executable
        run: chmod +x ./gradlew
      - name: build
        run: ./gradlew build
      - uses: Kir-Antipov/mc-publish@v3.3
        with:
          modrinth-id: RLrPqrNI
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}

          curseforge-id: 933674
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}

          github-token: ${{ secrets.GITHUB_TOKEN }}